{
 "title": "K8s Overview",
 "description": "K8s and nodes overview",
 "tags": [
  "k8s",
  "nodes"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "# of running k8s nodes",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(kubelet_node_name)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Amount of CPU activity per Node",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 8, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - avg by (instance)(rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\"}[1m])))*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage per Node",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 10, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance)( (1 -  node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)  * 100  )",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}